/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#faf8ff',
        'surface-dim': '#d2d9f4',
        'surface-bright': '#faf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f3ff',
        'surface-container': '#eaedff',
        'surface-container-high': '#e2e7ff',
        'surface-container-highest': '#dae2fd',
        'on-surface': '#131b2e',
        'on-surface-variant': '#404942',
        'inverse-surface': '#283044',
        'inverse-on-surface': '#eef0ff',
        'outline': '#707971',
        'outline-variant': '#bfc9c0',
        'surface-tint': '#226b47',
        'primary': '#004328',
        'on-primary': '#ffffff',
        'primary-container': '#0d5c3a',
        'on-primary-container': '#8ad2a7',
        'inverse-primary': '#8ed6aa',
        'secondary': '#a73a00',
        'on-secondary': '#ffffff',
        'secondary-container': '#fd651e',
        'on-secondary-container': '#571a00',
        'tertiary': '#00422b',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#005c3e',
        'on-tertiary-container': '#49da9f',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#a9f3c5',
        'primary-fixed-dim': '#8ed6aa',
        'on-primary-fixed': '#002111',
        'on-primary-fixed-variant': '#005232',
        'secondary-fixed': '#ffdbce',
        'secondary-fixed-dim': '#ffb599',
        'on-secondary-fixed': '#370e00',
        'on-secondary-fixed-variant': '#7f2b00',
        'tertiary-fixed': '#6ffbbe',
        'tertiary-fixed-dim': '#4edea3',
        'on-tertiary-fixed': '#002113',
        'on-tertiary-fixed-variant': '#005236',
        'background': '#faf8ff',
        'on-background': '#131b2e',
        'surface-variant': '#dae2fd',
      },
      borderRadius: {
        'sm': '0.25rem',
        'DEFAULT': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'gutter': '1rem',
        'gutter-desktop': '1.5rem',
        'margin': '1rem',
        'margin-desktop': '2rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-lg': '1rem',
        'space-xl': '1.5rem',
      },
      fontFamily: {
        'sans': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'label-sm': ['Plus Jakarta Sans'],
        'headline-xl-mobile': ['Plus Jakarta Sans'],
        'label-md': ['Plus Jakarta Sans'],
        'body-md': ['Plus Jakarta Sans'],
        'headline-xl': ['Plus Jakarta Sans'],
        'headline-md': ['Plus Jakarta Sans'],
        'body-lg': ['Plus Jakarta Sans'],
        'headline-lg': ['Plus Jakarta Sans'],
        'headline-lg-mobile': ['Plus Jakarta Sans'],
        'body-sm': ['Plus Jakarta Sans'],
        'label-lg': ['Plus Jakarta Sans'],
        'price-display': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'label-sm': ['11px', { lineHeight: '18px', letterSpacing: '0.04em', fontWeight: '700' }],
        'headline-xl-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'label-md': ['12px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-xl': ['36px', { lineHeight: '46px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '32px', fontWeight: '500' }],
        'headline-lg': ['28px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['22px', { lineHeight: '30px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'body-sm': ['12px', { lineHeight: '24px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '22px', letterSpacing: '0.01em', fontWeight: '700' }],
        'price-display': ['18px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '800' }],
      },
      lineHeight: {
        'academic': '2',
        '2': '2',
        'double': '2',
      },
    },
  },
  plugins: [],
};
